//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natterbase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int id { get; set; }
        public string action { get; set; }
        public string user_id { get; set; }
        public Nullable<byte> status { get; set; }
        public byte[] datecreated { get; set; }
    }
}
